# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spike_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1016, 768)
        self.horizontalLayout_23 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.pushButton_import = QtGui.QPushButton(Form)
        self.pushButton_import.setObjectName(_fromUtf8("pushButton_import"))
        self.verticalLayout_19.addWidget(self.pushButton_import)
        self.pushButton_load = QtGui.QPushButton(Form)
        self.pushButton_load.setObjectName(_fromUtf8("pushButton_load"))
        self.verticalLayout_19.addWidget(self.pushButton_load)
        self.verticalLayout_21.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_31 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_18.addWidget(self.label_31)
        self.listWidget_file = QtGui.QListWidget(Form)
        self.listWidget_file.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listWidget_file.setObjectName(_fromUtf8("listWidget_file"))
        self.verticalLayout_18.addWidget(self.listWidget_file)
        self.label_20 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_18.addWidget(self.label_20)
        self.listWidget_channel = QtGui.QListWidget(Form)
        self.listWidget_channel.setObjectName(_fromUtf8("listWidget_channel"))
        self.verticalLayout_18.addWidget(self.listWidget_channel)
        self.verticalLayout_20.addLayout(self.verticalLayout_18)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.pushButton_save = QtGui.QPushButton(Form)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.horizontalLayout_16.addWidget(self.pushButton_save)
        self.verticalLayout_20.addLayout(self.horizontalLayout_16)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.horizontalLayout_18.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(50, 178, 38);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_37 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_38 = QtGui.QVBoxLayout()
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.label_30 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_38.addWidget(self.label_30)
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.verticalLayout_38.addWidget(self.comboBox_2)
        self.horizontalLayout_22.addLayout(self.verticalLayout_38)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.label_29 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_35.addWidget(self.label_29)
        self.comboBox_noise = QtGui.QComboBox(self.tab)
        self.comboBox_noise.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_noise.setObjectName(_fromUtf8("comboBox_noise"))
        self.verticalLayout_35.addWidget(self.comboBox_noise)
        self.horizontalLayout_22.addLayout(self.verticalLayout_35)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.label_28 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_34.addWidget(self.label_28)
        self.comboBox_detection = QtGui.QComboBox(self.tab)
        self.comboBox_detection.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_detection.setObjectName(_fromUtf8("comboBox_detection"))
        self.verticalLayout_34.addWidget(self.comboBox_detection)
        self.horizontalLayout_22.addLayout(self.verticalLayout_34)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.label_26 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_33.addWidget(self.label_26)
        self.comboBox_correlation = QtGui.QComboBox(self.tab)
        self.comboBox_correlation.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_correlation.setObjectName(_fromUtf8("comboBox_correlation"))
        self.verticalLayout_33.addWidget(self.comboBox_correlation)
        self.horizontalLayout_22.addLayout(self.verticalLayout_33)
        self.verticalLayout_36.addLayout(self.horizontalLayout_22)
        spacerItem4 = QtGui.QSpacerItem(17, 17, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem4)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_27.addWidget(self.label_21)
        self.comboBox_cluster = QtGui.QComboBox(self.tab_2)
        self.comboBox_cluster.setEnabled(False)
        self.comboBox_cluster.setAutoFillBackground(False)
        self.comboBox_cluster.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_cluster.setObjectName(_fromUtf8("comboBox_cluster"))
        self.verticalLayout_27.addWidget(self.comboBox_cluster)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_28)
        self.line_8 = QtGui.QFrame(self.tab_2)
        self.line_8.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_15.addWidget(self.line_8)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_24.addWidget(self.label_23)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.radioButton_mean = QtGui.QRadioButton(self.tab_2)
        self.radioButton_mean.setObjectName(_fromUtf8("radioButton_mean"))
        self.verticalLayout_23.addWidget(self.radioButton_mean)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.radioButton_singleWave = QtGui.QRadioButton(self.tab_2)
        self.radioButton_singleWave.setObjectName(_fromUtf8("radioButton_singleWave"))
        self.verticalLayout_23.addWidget(self.radioButton_singleWave)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem7)
        self.radioButton_cluster = QtGui.QRadioButton(self.tab_2)
        self.radioButton_cluster.setObjectName(_fromUtf8("radioButton_cluster"))
        self.verticalLayout_23.addWidget(self.radioButton_cluster)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem8)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.horizontalLayout_15.addLayout(self.verticalLayout_24)
        self.line_9 = QtGui.QFrame(self.tab_2)
        self.line_9.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_15.addWidget(self.line_9)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_26.addWidget(self.label_24)
        self.comboBox = QtGui.QComboBox(self.tab_2)
        self.comboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_26.addWidget(self.comboBox)
        self.verticalLayout_29.addLayout(self.verticalLayout_26)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_29)
        self.line_10 = QtGui.QFrame(self.tab_2)
        self.line_10.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_15.addWidget(self.line_10)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_27 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_25.addWidget(self.label_27)
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-14, 0, 143, 250))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_19.addWidget(self.label_22)
        self.comboBox_color_1 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_color_1.setEnabled(False)
        self.comboBox_color_1.setAutoFillBackground(False)
        self.comboBox_color_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.comboBox_color_1.setObjectName(_fromUtf8("comboBox_color_1"))
        self.horizontalLayout_19.addWidget(self.comboBox_color_1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_25.addWidget(self.scrollArea)
        self.horizontalLayout_15.addLayout(self.verticalLayout_25)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_15)
        self.line_12 = QtGui.QFrame(self.tab_2)
        self.line_12.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout_20.addWidget(self.line_12)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.label_25 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_32.addWidget(self.label_25)
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 76, 267))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.checkBox_unit1 = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_unit1.setObjectName(_fromUtf8("checkBox_unit1"))
        self.horizontalLayout_21.addWidget(self.checkBox_unit1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_32.addWidget(self.scrollArea_2)
        self.horizontalLayout_20.addLayout(self.verticalLayout_32)
        self.pushButton_accept = QtGui.QPushButton(self.tab_2)
        self.pushButton_accept.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.pushButton_accept.setObjectName(_fromUtf8("pushButton_accept"))
        self.horizontalLayout_20.addWidget(self.pushButton_accept)
        self.verticalLayout_31.addLayout(self.horizontalLayout_20)
        self.line_11 = QtGui.QFrame(self.tab_2)
        self.line_11.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.verticalLayout_31.addWidget(self.line_11)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_none = QtGui.QRadioButton(self.tab_3)
        self.radioButton_none.setObjectName(_fromUtf8("radioButton_none"))
        self.verticalLayout.addWidget(self.radioButton_none)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.radioButton_sleep = QtGui.QRadioButton(self.tab_3)
        self.radioButton_sleep.setObjectName(_fromUtf8("radioButton_sleep"))
        self.verticalLayout.addWidget(self.radioButton_sleep)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.radioButton_behavior = QtGui.QRadioButton(self.tab_3)
        self.radioButton_behavior.setObjectName(_fromUtf8("radioButton_behavior"))
        self.verticalLayout.addWidget(self.radioButton_behavior)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.radioButton_externaltrigger = QtGui.QRadioButton(self.tab_3)
        self.radioButton_externaltrigger.setObjectName(_fromUtf8("radioButton_externaltrigger"))
        self.verticalLayout.addWidget(self.radioButton_externaltrigger)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem15)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioButton_psth = QtGui.QRadioButton(self.tab_3)
        self.radioButton_psth.setObjectName(_fromUtf8("radioButton_psth"))
        self.verticalLayout_3.addWidget(self.radioButton_psth)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.radioButton_raster = QtGui.QRadioButton(self.tab_3)
        self.radioButton_raster.setObjectName(_fromUtf8("radioButton_raster"))
        self.verticalLayout_3.addWidget(self.radioButton_raster)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.radioButton_raw = QtGui.QRadioButton(self.tab_3)
        self.radioButton_raw.setObjectName(_fromUtf8("radioButton_raw"))
        self.verticalLayout_3.addWidget(self.radioButton_raw)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.radioButton_waveforms = QtGui.QRadioButton(self.tab_3)
        self.radioButton_waveforms.setObjectName(_fromUtf8("radioButton_waveforms"))
        self.verticalLayout_3.addWidget(self.radioButton_waveforms)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.radioButton_events = QtGui.QRadioButton(self.tab_3)
        self.radioButton_events.setObjectName(_fromUtf8("radioButton_events"))
        self.verticalLayout_3.addWidget(self.radioButton_events)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_14.addWidget(self.line_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_7.addWidget(self.label_3)
        self.doubleSpinBox_binning = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_binning.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_binning.setObjectName(_fromUtf8("doubleSpinBox_binning"))
        self.verticalLayout_7.addWidget(self.doubleSpinBox_binning)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_14.addWidget(self.line_3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.label_4 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem24)
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.doubleSpinBox_min = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_min.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_min.setObjectName(_fromUtf8("doubleSpinBox_min"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_min)
        self.label_7 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.doubleSpinBox_max = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_max.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_max.setObjectName(_fromUtf8("doubleSpinBox_max"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_max)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem25)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.line_4 = QtGui.QFrame(self.tab_3)
        self.line_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_14.addWidget(self.line_4)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem26)
        self.label_8 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(self.tab_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.label_10 = QtGui.QLabel(self.tab_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.doubleSpinBox_startSpk = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startSpk.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_startSpk.setObjectName(_fromUtf8("doubleSpinBox_startSpk"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_startSpk)
        self.label_11 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.doubleSpinBox_stopSpk = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopSpk.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_stopSpk.setObjectName(_fromUtf8("doubleSpinBox_stopSpk"))
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_stopSpk)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_17.addLayout(self.verticalLayout_12)
        self.line_6 = QtGui.QFrame(self.tab_3)
        self.line_6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_17.addWidget(self.line_6)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.label_12 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem31)
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.doubleSpinBox_startSleep = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startSleep.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_startSleep.setObjectName(_fromUtf8("doubleSpinBox_startSleep"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_startSleep)
        self.label_15 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.doubleSpinBox_stopSleep = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopSleep.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_stopSleep.setObjectName(_fromUtf8("doubleSpinBox_stopSleep"))
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_stopSleep)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addLayout(self.verticalLayout_13)
        self.line_7 = QtGui.QFrame(self.tab_3)
        self.line_7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_17.addWidget(self.line_7)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.label_16 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.doubleSpinBox_startBehav = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startBehav.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_startBehav.setObjectName(_fromUtf8("doubleSpinBox_startBehav"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_startBehav)
        self.label_19 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_13.addWidget(self.label_19)
        self.doubleSpinBox_stopBehav = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopBehav.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.doubleSpinBox_stopBehav.setObjectName(_fromUtf8("doubleSpinBox_stopBehav"))
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_stopBehav)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        spacerItem35 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem35)
        self.horizontalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout_30.addLayout(self.horizontalLayout_14)
        self.line_5 = QtGui.QFrame(self.tab_3)
        self.line_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_30.addWidget(self.line_5)
        spacerItem36 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem36)
        self.line_5.raise_()
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_22.addWidget(self.tabWidget)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem37 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem37)
        self.pushButton_cancel = QtGui.QPushButton(Form)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_17.addWidget(self.pushButton_cancel)
        self.pushButton_done = QtGui.QPushButton(Form)
        self.pushButton_done.setObjectName(_fromUtf8("pushButton_done"))
        self.horizontalLayout_17.addWidget(self.pushButton_done)
        self.verticalLayout_22.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_22)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_18)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton_import.setText(_translate("Form", "Import data", None))
        self.pushButton_load.setText(_translate("Form", "Load data", None))
        self.label_31.setText(_translate("Form", "Select dataset:", None))
        self.label_20.setText(_translate("Form", "Select channel:", None))
        self.pushButton_save.setText(_translate("Form", "Save", None))
        self.label_30.setText(_translate("Form", "Reference", None))
        self.label_29.setText(_translate("Form", "Non linear energy operator", None))
        self.label_28.setText(_translate("Form", "Detection criteria", None))
        self.label_26.setText(_translate("Form", "Correlation criteria", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Detection", None))
        self.label_21.setText(_translate("Form", "Cluster", None))
        self.label_23.setText(_translate("Form", "Waveforms", None))
        self.radioButton_mean.setText(_translate("Form", "Mean", None))
        self.radioButton_singleWave.setText(_translate("Form", "Single waveforms", None))
        self.radioButton_cluster.setText(_translate("Form", "Cluster", None))
        self.label_24.setText(_translate("Form", "Session", None))
        self.label_27.setText(_translate("Form", "Color", None))
        self.label_22.setText(_translate("Form", "Unit1", None))
        self.label_25.setText(_translate("Form", "Change unit", None))
        self.checkBox_unit1.setText(_translate("Form", "unit 1", None))
        self.pushButton_accept.setText(_translate("Form", "Accept", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sorting", None))
        self.label.setText(_translate("Form", "Events", None))
        self.radioButton_none.setText(_translate("Form", "None", None))
        self.radioButton_sleep.setText(_translate("Form", "Sleep", None))
        self.radioButton_behavior.setText(_translate("Form", "Behavior", None))
        self.radioButton_externaltrigger.setText(_translate("Form", "External trigger", None))
        self.label_2.setText(_translate("Form", "Plot", None))
        self.radioButton_psth.setText(_translate("Form", "PSTH", None))
        self.radioButton_raster.setText(_translate("Form", "Raster", None))
        self.radioButton_raw.setText(_translate("Form", "Raw", None))
        self.radioButton_waveforms.setText(_translate("Form", "Waveform", None))
        self.radioButton_events.setText(_translate("Form", "Events", None))
        self.label_3.setText(_translate("Form", "Binning", None))
        self.label_4.setText(_translate("Form", "Range", None))
        self.label_5.setText(_translate("Form", "Min", None))
        self.label_6.setText(_translate("Form", "Max", None))
        self.label_7.setText(_translate("Form", "-", None))
        self.label_8.setText(_translate("Form", "Neuronal activity", None))
        self.label_9.setText(_translate("Form", "Start", None))
        self.label_10.setText(_translate("Form", "Stop", None))
        self.label_11.setText(_translate("Form", "-", None))
        self.label_12.setText(_translate("Form", "Sleep", None))
        self.label_13.setText(_translate("Form", "Start", None))
        self.label_14.setText(_translate("Form", "Stop", None))
        self.label_15.setText(_translate("Form", "-", None))
        self.label_16.setText(_translate("Form", "Behavior", None))
        self.label_17.setText(_translate("Form", "Start", None))
        self.label_18.setText(_translate("Form", "Stop", None))
        self.label_19.setText(_translate("Form", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Analysis", None))
        self.pushButton_cancel.setText(_translate("Form", "Cancel", None))
        self.pushButton_done.setText(_translate("Form", "Done", None))

