# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datainfodlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InfoDlg(object):
    def setupUi(self, InfoDlg):
        InfoDlg.setObjectName("InfoDlg")
        InfoDlg.resize(590, 403)
        InfoDlg.setToolTip("")
        InfoDlg.setSizeGripEnabled(False)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(InfoDlg)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(InfoDlg)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelName = QtWidgets.QLabel(InfoDlg)
        self.labelName.setObjectName("labelName")
        self.horizontalLayout.addWidget(self.labelName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidgetData = QtWidgets.QTableWidget(InfoDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetData.sizePolicy().hasHeightForWidth())
        self.tableWidgetData.setSizePolicy(sizePolicy)
        self.tableWidgetData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetData.setObjectName("tableWidgetData")
        self.tableWidgetData.setColumnCount(0)
        self.tableWidgetData.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidgetData)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.textBrowser = QtWidgets.QTextBrowser(InfoDlg)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(InfoDlg)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listWidgetTypes = QtWidgets.QListWidget(InfoDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetTypes.sizePolicy().hasHeightForWidth())
        self.listWidgetTypes.setSizePolicy(sizePolicy)
        self.listWidgetTypes.setMinimumSize(QtCore.QSize(100, 50))
        self.listWidgetTypes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidgetTypes.setObjectName("listWidgetTypes")
        self.horizontalLayout_5.addWidget(self.listWidgetTypes)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pushButtonEdit = QtWidgets.QPushButton(InfoDlg)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_4.addWidget(self.pushButtonEdit)
        self.pushButtonRestore = QtWidgets.QPushButton(InfoDlg)
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.horizontalLayout_4.addWidget(self.pushButtonRestore)
        self.pushButtonClose = QtWidgets.QPushButton(InfoDlg)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_4.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)

        self.retranslateUi(InfoDlg)
        QtCore.QMetaObject.connectSlotsByName(InfoDlg)

    def retranslateUi(self, InfoDlg):
        _translate = QtCore.QCoreApplication.translate
        InfoDlg.setWindowTitle(_translate("InfoDlg", "Info"))
        self.label.setText(_translate("InfoDlg", "Dataset:"))
        self.labelName.setText(_translate("InfoDlg", "TextLabel"))
        self.label_2.setText(_translate("InfoDlg", "Data Types:"))
        self.pushButtonEdit.setText(_translate("InfoDlg", "Edit Types"))
        self.pushButtonRestore.setText(_translate("InfoDlg", "Restore Types"))
        self.pushButtonClose.setText(_translate("InfoDlg", "Close"))

