# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'latencydlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExtractLatency(object):
    def setupUi(self, ExtractLatency):
        ExtractLatency.setObjectName("ExtractLatency")
        ExtractLatency.resize(653, 462)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ExtractLatency)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(ExtractLatency)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(ExtractLatency)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(ExtractLatency)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.InOutAllCombo = QtWidgets.QComboBox(ExtractLatency)
        self.InOutAllCombo.setObjectName("InOutAllCombo")
        self.InOutAllCombo.addItem("")
        self.InOutAllCombo.addItem("")
        self.InOutAllCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.InOutAllCombo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(ExtractLatency)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.timeStampsComboBox0 = QtWidgets.QComboBox(ExtractLatency)
        self.timeStampsComboBox0.setObjectName("timeStampsComboBox0")
        self.horizontalLayout.addWidget(self.timeStampsComboBox0)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(ExtractLatency)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.timeStampsComboBox1 = QtWidgets.QComboBox(ExtractLatency)
        self.timeStampsComboBox1.setObjectName("timeStampsComboBox1")
        self.horizontalLayout_4.addWidget(self.timeStampsComboBox1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(ExtractLatency)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(ExtractLatency)
        self.doubleSpinBox.setMaximum(99999.99)
        self.doubleSpinBox.setProperty("value", 30.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExtractLatency)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ExtractLatency)
        self.buttonBox.accepted.connect(ExtractLatency.accept)
        self.buttonBox.rejected.connect(ExtractLatency.reject)
        QtCore.QMetaObject.connectSlotsByName(ExtractLatency)

    def retranslateUi(self, ExtractLatency):
        _translate = QtCore.QCoreApplication.translate
        ExtractLatency.setWindowTitle(_translate("ExtractLatency", "Extract Latency"))
        self.label.setText(_translate("ExtractLatency", "Selected Dataset:"))
        self.label_2.setText(_translate("ExtractLatency", "Dataset"))
        self.label_5.setText(_translate("ExtractLatency", "Extract from:"))
        self.InOutAllCombo.setItemText(0, _translate("ExtractLatency", "All Dataset"))
        self.InOutAllCombo.setItemText(1, _translate("ExtractLatency", "Inside Trial"))
        self.InOutAllCombo.setItemText(2, _translate("ExtractLatency", "Outside Trial"))
        self.label_3.setText(_translate("ExtractLatency", "Trial Start:"))
        self.label_4.setText(_translate("ExtractLatency", "Trial End:"))
        self.label_6.setText(_translate("ExtractLatency", "Max Trial Duration"))

