# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mergedlg.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SelectDataset(object):
    def setupUi(self, SelectDataset):
        SelectDataset.setObjectName("SelectDataset")
        SelectDataset.resize(597, 348)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(SelectDataset)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAllDataset = QtWidgets.QLabel(SelectDataset)
        self.labelAllDataset.setObjectName("labelAllDataset")
        self.verticalLayout.addWidget(self.labelAllDataset)
        self.listWidgetAllDataset = QtWidgets.QListWidget(SelectDataset)
        self.listWidgetAllDataset.setObjectName("listWidgetAllDataset")
        self.verticalLayout.addWidget(self.listWidgetAllDataset)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelDatasetToMerge = QtWidgets.QLabel(SelectDataset)
        self.labelDatasetToMerge.setObjectName("labelDatasetToMerge")
        self.verticalLayout_2.addWidget(self.labelDatasetToMerge)
        self.listWidgetSelected = QtWidgets.QListWidget(SelectDataset)
        self.listWidgetSelected.setObjectName("listWidgetSelected")
        self.verticalLayout_2.addWidget(self.listWidgetSelected)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonUp = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.verticalLayout_3.addWidget(self.pushButtonUp)
        self.pushButtonAdd = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout_3.addWidget(self.pushButtonAdd)
        self.pushButtonNext = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.verticalLayout_3.addWidget(self.pushButtonNext)
        self.pushButtonRemove = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.verticalLayout_3.addWidget(self.pushButtonRemove)
        self.pushButtonDown = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.verticalLayout_3.addWidget(self.pushButtonDown)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelMergedName = QtWidgets.QLabel(SelectDataset)
        self.labelMergedName.setObjectName("labelMergedName")
        self.horizontalLayout_2.addWidget(self.labelMergedName)
        self.lineEditMergedName = QtWidgets.QLineEdit(SelectDataset)
        self.lineEditMergedName.setObjectName("lineEditMergedName")
        self.horizontalLayout_2.addWidget(self.lineEditMergedName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonOk = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(SelectDataset)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.labelAllDataset.setBuddy(self.listWidgetAllDataset)
        self.labelDatasetToMerge.setBuddy(self.listWidgetSelected)
        self.labelMergedName.setBuddy(self.lineEditMergedName)

        self.retranslateUi(SelectDataset)
        self.pushButtonCancel.clicked.connect(SelectDataset.reject)
        QtCore.QMetaObject.connectSlotsByName(SelectDataset)
        SelectDataset.setTabOrder(self.listWidgetAllDataset, self.listWidgetSelected)
        SelectDataset.setTabOrder(self.listWidgetSelected, self.lineEditMergedName)
        SelectDataset.setTabOrder(self.lineEditMergedName, self.pushButtonUp)
        SelectDataset.setTabOrder(self.pushButtonUp, self.pushButtonRemove)
        SelectDataset.setTabOrder(self.pushButtonRemove, self.pushButtonDown)

    def retranslateUi(self, SelectDataset):
        _translate = QtCore.QCoreApplication.translate
        SelectDataset.setWindowTitle(_translate("SelectDataset", "Dialog"))
        self.labelAllDataset.setText(_translate("SelectDataset", "&Select  dataset:"))
        self.labelDatasetToMerge.setText(_translate("SelectDataset", "&Dataset to merge:"))
        self.pushButtonUp.setText(_translate("SelectDataset", "Up"))
        self.pushButtonAdd.setText(_translate("SelectDataset", "Add"))
        self.pushButtonNext.setText(_translate("SelectDataset", "Next"))
        self.pushButtonRemove.setText(_translate("SelectDataset", "Remove"))
        self.pushButtonDown.setText(_translate("SelectDataset", "Down"))
        self.labelMergedName.setText(_translate("SelectDataset", "&Dataset Names (separated by ;):"))
        self.pushButtonOk.setText(_translate("SelectDataset", "Ok"))
        self.pushButtonCancel.setText(_translate("SelectDataset", "Cancel"))

