# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetSleepRecordingPhase.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 358)
        Form.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_phase_sel = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_phase_sel.setFont(font)
        self.groupBox_phase_sel.setStyleSheet("")
        self.groupBox_phase_sel.setObjectName("groupBox_phase_sel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_phase_sel)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_phase_sel)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dateTimeEdit_bs_0 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_bs_0.setFont(font)
        self.dateTimeEdit_bs_0.setObjectName("dateTimeEdit_bs_0")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_bs_0)
        self.label_6 = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.dateTimeEdit_bs_1 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_bs_1.setFont(font)
        self.dateTimeEdit_bs_1.setObjectName("dateTimeEdit_bs_1")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_bs_1)
        self.checkBox_bs = QtWidgets.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_bs.setText("")
        self.checkBox_bs.setObjectName("checkBox_bs")
        self.horizontalLayout_4.addWidget(self.checkBox_bs)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateTimeEdit_sd_0 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_sd_0.setFont(font)
        self.dateTimeEdit_sd_0.setObjectName("dateTimeEdit_sd_0")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_sd_0)
        self.label_5 = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dateTimeEdit_sd_1 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_sd_1.setFont(font)
        self.dateTimeEdit_sd_1.setObjectName("dateTimeEdit_sd_1")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_sd_1)
        self.checkBox_sd = QtWidgets.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_sd.setText("")
        self.checkBox_sd.setObjectName("checkBox_sd")
        self.horizontalLayout_3.addWidget(self.checkBox_sd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dateTimeEdit_rc_0 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_rc_0.setFont(font)
        self.dateTimeEdit_rc_0.setObjectName("dateTimeEdit_rc_0")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_rc_0)
        self.label_4 = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_rc_1 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_rc_1.setFont(font)
        self.dateTimeEdit_rc_1.setObjectName("dateTimeEdit_rc_1")
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_rc_1)
        self.checkBox_rc = QtWidgets.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_rc.setText("")
        self.checkBox_rc.setObjectName("checkBox_rc")
        self.horizontalLayout_2.addWidget(self.checkBox_rc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dateTimeEdit_norm0 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        self.dateTimeEdit_norm0.setObjectName("dateTimeEdit_norm0")
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_norm0)
        self.label_9 = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.dateTimeEdit_norm1 = QtWidgets.QDateTimeEdit(self.groupBox_phase_sel)
        self.dateTimeEdit_norm1.setObjectName("dateTimeEdit_norm1")
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_norm1)
        self.checkBox_noNorm = QtWidgets.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_noNorm.setObjectName("checkBox_noNorm")
        self.horizontalLayout_7.addWidget(self.checkBox_noNorm)
        spacerItem1 = QtWidgets.QSpacerItem(58, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_warning = QtWidgets.QLabel(self.groupBox_phase_sel)
        self.label_warning.setObjectName("label_warning")
        self.horizontalLayout.addWidget(self.label_warning)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_phase_sel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_phase_sel.setTitle(_translate("Form", "Phase Selection"))
        self.label.setText(_translate("Form", "Baseline"))
        self.label_3.setText(_translate("Form", "Sleep Deprivation"))
        self.label_2.setText(_translate("Form", "Rebound"))
        self.label_8.setText(_translate("Form", "Norm Range"))
        self.label_6.setText(_translate("Form", "-"))
        self.label_5.setText(_translate("Form", "-"))
        self.label_4.setText(_translate("Form", "-"))
        self.label_9.setText(_translate("Form", "-"))
        self.checkBox_noNorm.setText(_translate("Form", "No norm"))
        self.label_warning.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "Apply to"))

