# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetSleepRecordingPhase.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(546, 358)
        Form.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_phase_sel = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_phase_sel.setFont(font)
        self.groupBox_phase_sel.setStyleSheet(_fromUtf8(""))
        self.groupBox_phase_sel.setObjectName(_fromUtf8("groupBox_phase_sel"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_phase_sel)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBox = QtGui.QComboBox(self.groupBox_phase_sel)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_6.addWidget(self.comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_8 = QtGui.QLabel(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.dateTimeEdit_bs_0 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_bs_0.setFont(font)
        self.dateTimeEdit_bs_0.setObjectName(_fromUtf8("dateTimeEdit_bs_0"))
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_bs_0)
        self.label_6 = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.dateTimeEdit_bs_1 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_bs_1.setFont(font)
        self.dateTimeEdit_bs_1.setObjectName(_fromUtf8("dateTimeEdit_bs_1"))
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_bs_1)
        self.checkBox_bs = QtGui.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_bs.setText(_fromUtf8(""))
        self.checkBox_bs.setObjectName(_fromUtf8("checkBox_bs"))
        self.horizontalLayout_4.addWidget(self.checkBox_bs)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dateTimeEdit_sd_0 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_sd_0.setFont(font)
        self.dateTimeEdit_sd_0.setObjectName(_fromUtf8("dateTimeEdit_sd_0"))
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_sd_0)
        self.label_5 = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dateTimeEdit_sd_1 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_sd_1.setFont(font)
        self.dateTimeEdit_sd_1.setObjectName(_fromUtf8("dateTimeEdit_sd_1"))
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_sd_1)
        self.checkBox_sd = QtGui.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_sd.setText(_fromUtf8(""))
        self.checkBox_sd.setObjectName(_fromUtf8("checkBox_sd"))
        self.horizontalLayout_3.addWidget(self.checkBox_sd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dateTimeEdit_rc_0 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_rc_0.setFont(font)
        self.dateTimeEdit_rc_0.setObjectName(_fromUtf8("dateTimeEdit_rc_0"))
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_rc_0)
        self.label_4 = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dateTimeEdit_rc_1 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_rc_1.setFont(font)
        self.dateTimeEdit_rc_1.setObjectName(_fromUtf8("dateTimeEdit_rc_1"))
        self.horizontalLayout_2.addWidget(self.dateTimeEdit_rc_1)
        self.checkBox_rc = QtGui.QCheckBox(self.groupBox_phase_sel)
        self.checkBox_rc.setText(_fromUtf8(""))
        self.checkBox_rc.setObjectName(_fromUtf8("checkBox_rc"))
        self.horizontalLayout_2.addWidget(self.checkBox_rc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.dateTimeEdit_norm0 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        self.dateTimeEdit_norm0.setObjectName(_fromUtf8("dateTimeEdit_norm0"))
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_norm0)
        self.label_9 = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.dateTimeEdit_norm1 = QtGui.QDateTimeEdit(self.groupBox_phase_sel)
        self.dateTimeEdit_norm1.setObjectName(_fromUtf8("dateTimeEdit_norm1"))
        self.horizontalLayout_7.addWidget(self.dateTimeEdit_norm1)
        spacerItem1 = QtGui.QSpacerItem(58, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.label_warning = QtGui.QLabel(self.groupBox_phase_sel)
        self.label_warning.setObjectName(_fromUtf8("label_warning"))
        self.horizontalLayout.addWidget(self.label_warning)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtGui.QPushButton(self.groupBox_phase_sel)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_phase_sel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox_phase_sel.setTitle(_translate("Form", "Phase Selection", None))
        self.label.setText(_translate("Form", "Baseline", None))
        self.label_3.setText(_translate("Form", "Sleep Deprivation", None))
        self.label_2.setText(_translate("Form", "Recovery", None))
        self.label_8.setText(_translate("Form", "Norm Range", None))
        self.label_6.setText(_translate("Form", "-", None))
        self.label_5.setText(_translate("Form", "-", None))
        self.label_4.setText(_translate("Form", "-", None))
        self.label_9.setText(_translate("Form", "-", None))
        self.label_warning.setText(_translate("Form", "TextLabel", None))
        self.pushButton.setText(_translate("Form", "Apply to", None))

