# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'microsystem_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1054, 741)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.scrollArea_Box = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_Box.setMinimumSize(QtCore.QSize(150, 0))
        self.scrollArea_Box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea_Box.setWidgetResizable(True)
        self.scrollArea_Box.setObjectName(_fromUtf8("scrollArea_Box"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 664))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_18.addWidget(self.label_7)
        self.horizontalLayout_31.addLayout(self.verticalLayout_18)
        self.scrollArea_Box.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_30.addWidget(self.scrollArea_Box)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setMaximumSize(QtCore.QSize(800, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 721, 664))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(65, 105, 255);\n"
""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_date_time = QtGui.QWidget()
        self.tab_date_time.setObjectName(_fromUtf8("tab_date_time"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.tab_date_time)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.groupBox_datetime = QtGui.QGroupBox(self.tab_date_time)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_datetime.setFont(font)
        self.groupBox_datetime.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_datetime.setObjectName(_fromUtf8("groupBox_datetime"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_datetime)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.radioButton_read_time = QtGui.QRadioButton(self.groupBox_datetime)
        self.radioButton_read_time.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color:disabled  rgb(255, 170, 0);"))
        self.radioButton_read_time.setObjectName(_fromUtf8("radioButton_read_time"))
        self.verticalLayout_8.addWidget(self.radioButton_read_time)
        self.radioButton_read_date = QtGui.QRadioButton(self.groupBox_datetime)
        self.radioButton_read_date.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color:disabled  rgb(255, 170, 0);"))
        self.radioButton_read_date.setObjectName(_fromUtf8("radioButton_read_date"))
        self.verticalLayout_8.addWidget(self.radioButton_read_date)
        self.horizontalLayout_15.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.radioButton_set_dateTime = QtGui.QRadioButton(self.groupBox_datetime)
        self.radioButton_set_dateTime.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color:disabled  rgb(255, 170, 0);"))
        self.radioButton_set_dateTime.setObjectName(_fromUtf8("radioButton_set_dateTime"))
        self.verticalLayout_9.addWidget(self.radioButton_set_dateTime)
        self.horizontalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.pushButton_send_datetime = QtGui.QPushButton(self.groupBox_datetime)
        self.pushButton_send_datetime.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);"))
        self.pushButton_send_datetime.setObjectName(_fromUtf8("pushButton_send_datetime"))
        self.horizontalLayout_14.addWidget(self.pushButton_send_datetime)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.verticalLayout_10)
        self.horizontalLayout_17.addWidget(self.groupBox_datetime)
        self.tabWidget.addTab(self.tab_date_time, _fromUtf8(""))
        self.tab_actuate = QtGui.QWidget()
        self.tab_actuate.setObjectName(_fromUtf8("tab_actuate"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_actuate)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_actuate = QtGui.QGroupBox(self.tab_actuate)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_actuate.setFont(font)
        self.groupBox_actuate.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_actuate.setObjectName(_fromUtf8("groupBox_actuate"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_actuate)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_release_pellet = QtGui.QRadioButton(self.groupBox_actuate)
        self.radioButton_release_pellet.setObjectName(_fromUtf8("radioButton_release_pellet"))
        self.horizontalLayout_2.addWidget(self.radioButton_release_pellet)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_light_on = QtGui.QRadioButton(self.groupBox_actuate)
        self.radioButton_light_on.setObjectName(_fromUtf8("radioButton_light_on"))
        self.verticalLayout_2.addWidget(self.radioButton_light_on)
        self.radioButton_sound_on = QtGui.QRadioButton(self.groupBox_actuate)
        self.radioButton_sound_on.setObjectName(_fromUtf8("radioButton_sound_on"))
        self.verticalLayout_2.addWidget(self.radioButton_sound_on)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_light_off = QtGui.QRadioButton(self.groupBox_actuate)
        self.radioButton_light_off.setObjectName(_fromUtf8("radioButton_light_off"))
        self.verticalLayout.addWidget(self.radioButton_light_off)
        self.radioButton_sound_off = QtGui.QRadioButton(self.groupBox_actuate)
        self.radioButton_sound_off.setObjectName(_fromUtf8("radioButton_sound_off"))
        self.verticalLayout.addWidget(self.radioButton_sound_off)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_left = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_left.setObjectName(_fromUtf8("checkBox_left"))
        self.horizontalLayout_3.addWidget(self.checkBox_left)
        self.checkBox_center = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_center.setObjectName(_fromUtf8("checkBox_center"))
        self.horizontalLayout_3.addWidget(self.checkBox_center)
        self.checkBox_right = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_right.setObjectName(_fromUtf8("checkBox_right"))
        self.horizontalLayout_3.addWidget(self.checkBox_right)
        self.checkBox_all = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_all.setObjectName(_fromUtf8("checkBox_all"))
        self.horizontalLayout_3.addWidget(self.checkBox_all)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_send_actuate = QtGui.QPushButton(self.groupBox_actuate)
        self.pushButton_send_actuate.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"background-color: rgb(170, 170, 255);"))
        self.pushButton_send_actuate.setObjectName(_fromUtf8("pushButton_send_actuate"))
        self.horizontalLayout_4.addWidget(self.pushButton_send_actuate)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_blu = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_blu.setObjectName(_fromUtf8("checkBox_blu"))
        self.verticalLayout_3.addWidget(self.checkBox_blu)
        self.checkBox_green = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_green.setObjectName(_fromUtf8("checkBox_green"))
        self.verticalLayout_3.addWidget(self.checkBox_green)
        self.checkBox_cyano = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_cyano.setObjectName(_fromUtf8("checkBox_cyano"))
        self.verticalLayout_3.addWidget(self.checkBox_cyano)
        self.checkBox_red = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_red.setObjectName(_fromUtf8("checkBox_red"))
        self.verticalLayout_3.addWidget(self.checkBox_red)
        self.checkBox_violet = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_violet.setObjectName(_fromUtf8("checkBox_violet"))
        self.verticalLayout_3.addWidget(self.checkBox_violet)
        self.checkBox_yellow = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_yellow.setObjectName(_fromUtf8("checkBox_yellow"))
        self.verticalLayout_3.addWidget(self.checkBox_yellow)
        self.checkBox_white = QtGui.QCheckBox(self.groupBox_actuate)
        self.checkBox_white.setObjectName(_fromUtf8("checkBox_white"))
        self.verticalLayout_3.addWidget(self.checkBox_white)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addWidget(self.groupBox_actuate)
        self.tabWidget.addTab(self.tab_actuate, _fromUtf8(""))
        self.tab_get_set = QtGui.QWidget()
        self.tab_get_set.setObjectName(_fromUtf8("tab_get_set"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_get_set)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_other_gs = QtGui.QGroupBox(self.tab_get_set)
        self.groupBox_other_gs.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_other_gs.setObjectName(_fromUtf8("groupBox_other_gs"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_other_gs)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_noise_frequency = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_noise_frequency.setObjectName(_fromUtf8("radioButton_noise_frequency"))
        self.verticalLayout_5.addWidget(self.radioButton_noise_frequency)
        self.radioButton_exp_id = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_exp_id.setObjectName(_fromUtf8("radioButton_exp_id"))
        self.verticalLayout_5.addWidget(self.radioButton_exp_id)
        self.radioButton_phase = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_phase.setObjectName(_fromUtf8("radioButton_phase"))
        self.verticalLayout_5.addWidget(self.radioButton_phase)
        self.radioButton_box_id = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_box_id.setObjectName(_fromUtf8("radioButton_box_id"))
        self.verticalLayout_5.addWidget(self.radioButton_box_id)
        self.radioButton_subject = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_subject.setObjectName(_fromUtf8("radioButton_subject"))
        self.verticalLayout_5.addWidget(self.radioButton_subject)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButton_poke_th_left = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_poke_th_left.setObjectName(_fromUtf8("radioButton_poke_th_left"))
        self.verticalLayout_6.addWidget(self.radioButton_poke_th_left)
        self.radioButton_poke_th_center = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_poke_th_center.setObjectName(_fromUtf8("radioButton_poke_th_center"))
        self.verticalLayout_6.addWidget(self.radioButton_poke_th_center)
        self.radioButton_poke_th_right = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_poke_th_right.setObjectName(_fromUtf8("radioButton_poke_th_right"))
        self.verticalLayout_6.addWidget(self.radioButton_poke_th_right)
        self.radioButton_max_trial_num = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_max_trial_num.setObjectName(_fromUtf8("radioButton_max_trial_num"))
        self.verticalLayout_6.addWidget(self.radioButton_max_trial_num)
        self.radioButton_trial_timeout = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_trial_timeout.setObjectName(_fromUtf8("radioButton_trial_timeout"))
        self.verticalLayout_6.addWidget(self.radioButton_trial_timeout)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_mean_distr = QtGui.QRadioButton(self.groupBox_other_gs)
        self.radioButton_mean_distr.setObjectName(_fromUtf8("radioButton_mean_distr"))
        self.horizontalLayout_8.addWidget(self.radioButton_mean_distr)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_2 = QtGui.QLabel(self.groupBox_other_gs)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.spinBox_param1 = QtGui.QSpinBox(self.groupBox_other_gs)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.spinBox_param1.setPalette(palette)
        self.spinBox_param1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_param1.setMaximum(255)
        self.spinBox_param1.setObjectName(_fromUtf8("spinBox_param1"))
        self.horizontalLayout_9.addWidget(self.spinBox_param1)
        self.label_3 = QtGui.QLabel(self.groupBox_other_gs)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.spinBox_param2 = QtGui.QSpinBox(self.groupBox_other_gs)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.spinBox_param2.setPalette(palette)
        self.spinBox_param2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_param2.setMaximum(255)
        self.spinBox_param2.setObjectName(_fromUtf8("spinBox_param2"))
        self.horizontalLayout_9.addWidget(self.spinBox_param2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_get = QtGui.QCheckBox(self.groupBox_other_gs)
        self.checkBox_get.setObjectName(_fromUtf8("checkBox_get"))
        self.horizontalLayout_10.addWidget(self.checkBox_get)
        self.checkBox_set = QtGui.QCheckBox(self.groupBox_other_gs)
        self.checkBox_set.setObjectName(_fromUtf8("checkBox_set"))
        self.horizontalLayout_10.addWidget(self.checkBox_set)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pushButton_send_other_gs = QtGui.QPushButton(self.groupBox_other_gs)
        self.pushButton_send_other_gs.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);"))
        self.pushButton_send_other_gs.setObjectName(_fromUtf8("pushButton_send_other_gs"))
        self.horizontalLayout_10.addWidget(self.pushButton_send_other_gs)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.horizontalLayout_13.addWidget(self.groupBox_other_gs)
        self.tabWidget.addTab(self.tab_get_set, _fromUtf8(""))
        self.tab_other = QtGui.QWidget()
        self.tab_other.setObjectName(_fromUtf8("tab_other"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.tab_other)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.groupBox_other_g = QtGui.QGroupBox(self.tab_other)
        self.groupBox_other_g.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox_other_g.setObjectName(_fromUtf8("groupBox_other_g"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.groupBox_other_g)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.radioButton_fw = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_fw.setObjectName(_fromUtf8("radioButton_fw"))
        self.verticalLayout_11.addWidget(self.radioButton_fw)
        self.radioButton_ic2_status = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_ic2_status.setObjectName(_fromUtf8("radioButton_ic2_status"))
        self.verticalLayout_11.addWidget(self.radioButton_ic2_status)
        self.radioButton_startAlone = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_startAlone.setObjectName(_fromUtf8("radioButton_startAlone"))
        self.verticalLayout_11.addWidget(self.radioButton_startAlone)
        self.radioButton_prog_size = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_prog_size.setObjectName(_fromUtf8("radioButton_prog_size"))
        self.verticalLayout_11.addWidget(self.radioButton_prog_size)
        self.horizontalLayout_19.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.radioButton_bactery_level = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_bactery_level.setObjectName(_fromUtf8("radioButton_bactery_level"))
        self.verticalLayout_12.addWidget(self.radioButton_bactery_level)
        self.radioButton_trial_num = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_trial_num.setObjectName(_fromUtf8("radioButton_trial_num"))
        self.verticalLayout_12.addWidget(self.radioButton_trial_num)
        self.radioButton_stopAlone = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_stopAlone.setObjectName(_fromUtf8("radioButton_stopAlone"))
        self.verticalLayout_12.addWidget(self.radioButton_stopAlone)
        self.radioButton_readTrialTime = QtGui.QRadioButton(self.groupBox_other_g)
        self.radioButton_readTrialTime.setObjectName(_fromUtf8("radioButton_readTrialTime"))
        self.verticalLayout_12.addWidget(self.radioButton_readTrialTime)
        self.horizontalLayout_19.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.pushButton_send_other_g = QtGui.QPushButton(self.groupBox_other_g)
        self.pushButton_send_other_g.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);"))
        self.pushButton_send_other_g.setObjectName(_fromUtf8("pushButton_send_other_g"))
        self.horizontalLayout_18.addWidget(self.pushButton_send_other_g)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_21.addLayout(self.verticalLayout_13)
        self.horizontalLayout_20.addWidget(self.groupBox_other_g)
        self.tabWidget.addTab(self.tab_other, _fromUtf8(""))
        self.tab_custom = QtGui.QWidget()
        self.tab_custom.setObjectName(_fromUtf8("tab_custom"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout(self.tab_custom)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.groupBox = QtGui.QGroupBox(self.tab_custom)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 145, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 145, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 145, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 105, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_22.addWidget(self.label_17)
        self.spinBox = QtGui.QSpinBox(self.groupBox)
        self.spinBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(8)
        self.spinBox.setProperty("value", 8)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_22.addWidget(self.spinBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem6)
        self.verticalLayout_14.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_25.addWidget(self.label_16)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem7)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.spinBox_msg1 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg1.setMaximum(255)
        self.spinBox_msg1.setObjectName(_fromUtf8("spinBox_msg1"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_23.addWidget(self.label_13)
        self.spinBox_msg2 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg2.setMaximum(255)
        self.spinBox_msg2.setObjectName(_fromUtf8("spinBox_msg2"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg2)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_23.addWidget(self.label_10)
        self.spinBox_msg3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg3.setMaximum(255)
        self.spinBox_msg3.setObjectName(_fromUtf8("spinBox_msg3"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg3)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_23.addWidget(self.label_11)
        self.spinBox_msg4 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg4.setMaximum(255)
        self.spinBox_msg4.setObjectName(_fromUtf8("spinBox_msg4"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg4)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_23.addWidget(self.label_12)
        self.spinBox_msg5 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg5.setMaximum(255)
        self.spinBox_msg5.setObjectName(_fromUtf8("spinBox_msg5"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg5)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_23.addWidget(self.label_19)
        self.spinBox_msg6 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg6.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg6.setMaximum(255)
        self.spinBox_msg6.setObjectName(_fromUtf8("spinBox_msg6"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg6)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.spinBox_msg7 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg7.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg7.setMaximum(255)
        self.spinBox_msg7.setObjectName(_fromUtf8("spinBox_msg7"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg7)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_23.addWidget(self.label_15)
        self.spinBox_msg8 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_msg8.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        self.spinBox_msg8.setMaximum(255)
        self.spinBox_msg8.setObjectName(_fromUtf8("spinBox_msg8"))
        self.horizontalLayout_23.addWidget(self.spinBox_msg8)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem8)
        self.pushButton_send_custom = QtGui.QPushButton(self.groupBox)
        self.pushButton_send_custom.setStyleSheet(_fromUtf8("background-color: rgb(170, 170, 255);\n"
"color: rgb(0, 0, 0);"))
        self.pushButton_send_custom.setObjectName(_fromUtf8("pushButton_send_custom"))
        self.horizontalLayout_24.addWidget(self.pushButton_send_custom)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26.addLayout(self.verticalLayout_14)
        self.horizontalLayout_27.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_custom, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.tabWidget)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_28.addWidget(self.label_18)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.tableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 34))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_15.addWidget(self.tableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.pushButton__reset = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton__reset.setObjectName(_fromUtf8("pushButton__reset"))
        self.horizontalLayout.addWidget(self.pushButton__reset)
        self.pushButton_done = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_done.setObjectName(_fromUtf8("pushButton_done"))
        self.horizontalLayout.addWidget(self.pushButton_done)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.horizontalLayout_29.addLayout(self.verticalLayout_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_30.addWidget(self.scrollArea)
        self.verticalLayout_17.addLayout(self.horizontalLayout_30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_7.setText(_translate("MainWindow", "Select Box:", None))
        self.groupBox_datetime.setTitle(_translate("MainWindow", "Date and Time", None))
        self.radioButton_read_time.setText(_translate("MainWindow", "Read Time", None))
        self.radioButton_read_date.setText(_translate("MainWindow", "Read Date", None))
        self.radioButton_set_dateTime.setText(_translate("MainWindow", "Set current date and time ", None))
        self.pushButton_send_datetime.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_date_time), _translate("MainWindow", "Date & Time", None))
        self.groupBox_actuate.setTitle(_translate("MainWindow", "Actuate Feeder", None))
        self.radioButton_release_pellet.setText(_translate("MainWindow", "Release Pellet", None))
        self.radioButton_light_on.setText(_translate("MainWindow", "Light On", None))
        self.radioButton_sound_on.setText(_translate("MainWindow", "Sound On", None))
        self.radioButton_light_off.setText(_translate("MainWindow", "Light Off", None))
        self.radioButton_sound_off.setText(_translate("MainWindow", "Sound Off", None))
        self.checkBox_left.setText(_translate("MainWindow", "Left", None))
        self.checkBox_center.setText(_translate("MainWindow", "Center", None))
        self.checkBox_right.setText(_translate("MainWindow", "Right", None))
        self.checkBox_all.setText(_translate("MainWindow", "All", None))
        self.pushButton_send_actuate.setText(_translate("MainWindow", "Send", None))
        self.checkBox_blu.setText(_translate("MainWindow", "Blu", None))
        self.checkBox_green.setText(_translate("MainWindow", "Green", None))
        self.checkBox_cyano.setText(_translate("MainWindow", "Cyano", None))
        self.checkBox_red.setText(_translate("MainWindow", "Red", None))
        self.checkBox_violet.setText(_translate("MainWindow", "Violet", None))
        self.checkBox_yellow.setText(_translate("MainWindow", "Yellow", None))
        self.checkBox_white.setText(_translate("MainWindow", "White", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_actuate), _translate("MainWindow", "Actuate Feeder", None))
        self.groupBox_other_gs.setTitle(_translate("MainWindow", "Other Commands (Get/Set)", None))
        self.radioButton_noise_frequency.setText(_translate("MainWindow", "Noise Frequency", None))
        self.radioButton_exp_id.setText(_translate("MainWindow", "Experiment ID", None))
        self.radioButton_phase.setText(_translate("MainWindow", "Phase", None))
        self.radioButton_box_id.setText(_translate("MainWindow", "Box ID", None))
        self.radioButton_subject.setText(_translate("MainWindow", "Subject", None))
        self.radioButton_poke_th_left.setText(_translate("MainWindow", "Poke Threshold Left", None))
        self.radioButton_poke_th_center.setText(_translate("MainWindow", "Poke Threshold Center", None))
        self.radioButton_poke_th_right.setText(_translate("MainWindow", "Poke Threshold Right", None))
        self.radioButton_max_trial_num.setText(_translate("MainWindow", "Max Trial Number", None))
        self.radioButton_trial_timeout.setText(_translate("MainWindow", "Trial Timeout", None))
        self.radioButton_mean_distr.setText(_translate("MainWindow", "Mean Distribution", None))
        self.label_2.setText(_translate("MainWindow", "Parameter:", None))
        self.label_3.setText(_translate("MainWindow", "-", None))
        self.checkBox_get.setText(_translate("MainWindow", "Get", None))
        self.checkBox_set.setText(_translate("MainWindow", "Set", None))
        self.pushButton_send_other_gs.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_get_set), _translate("MainWindow", "Get & Set", None))
        self.groupBox_other_g.setTitle(_translate("MainWindow", "Other Commands (Get only)", None))
        self.radioButton_fw.setText(_translate("MainWindow", "Firmware Version", None))
        self.radioButton_ic2_status.setText(_translate("MainWindow", "IC2 Status", None))
        self.radioButton_startAlone.setText(_translate("MainWindow", "Start Stand Alone", None))
        self.radioButton_prog_size.setText(_translate("MainWindow", "Program Size", None))
        self.radioButton_bactery_level.setText(_translate("MainWindow", "Bactery Level", None))
        self.radioButton_trial_num.setText(_translate("MainWindow", "Trial Number", None))
        self.radioButton_stopAlone.setText(_translate("MainWindow", "Stop Stand Alone", None))
        self.radioButton_readTrialTime.setText(_translate("MainWindow", "Read trial time", None))
        self.pushButton_send_other_g.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), _translate("MainWindow", "Others", None))
        self.groupBox.setTitle(_translate("MainWindow", "Custom Messages", None))
        self.label_17.setText(_translate("MainWindow", "Length: ", None))
        self.label_16.setText(_translate("MainWindow", "Message:", None))
        self.label_13.setText(_translate("MainWindow", "-", None))
        self.label_10.setText(_translate("MainWindow", "-", None))
        self.label_11.setText(_translate("MainWindow", "-", None))
        self.label_12.setText(_translate("MainWindow", "-", None))
        self.label_19.setText(_translate("MainWindow", "-", None))
        self.label_14.setText(_translate("MainWindow", "-", None))
        self.label_15.setText(_translate("MainWindow", "-", None))
        self.pushButton_send_custom.setText(_translate("MainWindow", "Send", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_custom), _translate("MainWindow", "Custom Messages", None))
        self.label_18.setText(_translate("MainWindow", "Read Messages:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Box ID", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R/W", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Row Message", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Translation", None))
        self.pushButton__reset.setText(_translate("MainWindow", "Clear", None))
        self.pushButton_done.setText(_translate("MainWindow", "Close", None))

