# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setupLightCycle.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


def _fromUtf8(s):
    return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(879, 667)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.scrollAreaBox = QtWidgets.QScrollArea(Dialog)
        self.scrollAreaBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollAreaBox.setWidgetResizable(True)
        self.scrollAreaBox.setObjectName(_fromUtf8("scrollAreaBox"))
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 198, 571))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBoxSelectAll = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBoxSelectAll.setObjectName(_fromUtf8("checkBoxSelectAll"))
        self.verticalLayout_6.addWidget(self.checkBoxSelectAll)
        self.scrollAreaBox.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.scrollAreaBox)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 0))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 838, 550))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBoxCL = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxCL.setObjectName(_fromUtf8("spinBoxCL"))
        self.horizontalLayout_3.addWidget(self.spinBoxCL)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBoxL1 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL1.setObjectName(_fromUtf8("spinBoxL1"))
        self.horizontalLayout_2.addWidget(self.spinBoxL1)
        self.spinBoxL2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL2.setObjectName(_fromUtf8("spinBoxL2"))
        self.horizontalLayout_2.addWidget(self.spinBoxL2)
        self.spinBoxL3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL3.setObjectName(_fromUtf8("spinBoxL3"))
        self.horizontalLayout_2.addWidget(self.spinBoxL3)
        self.spinBoxL4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL4.setObjectName(_fromUtf8("spinBoxL4"))
        self.horizontalLayout_2.addWidget(self.spinBoxL4)
        self.spinBoxL5 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL5.setObjectName(_fromUtf8("spinBoxL5"))
        self.horizontalLayout_2.addWidget(self.spinBoxL5)
        self.spinBoxL6 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL6.setObjectName(_fromUtf8("spinBoxL6"))
        self.horizontalLayout_2.addWidget(self.spinBoxL6)
        self.spinBoxL7 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL7.setObjectName(_fromUtf8("spinBoxL7"))
        self.horizontalLayout_2.addWidget(self.spinBoxL7)
        self.spinBoxL8 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL8.setObjectName(_fromUtf8("spinBoxL8"))
        self.horizontalLayout_2.addWidget(self.spinBoxL8)
        self.spinBoxL9 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL9.setObjectName(_fromUtf8("spinBoxL9"))
        self.horizontalLayout_2.addWidget(self.spinBoxL9)
        self.spinBoxL10 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL10.setObjectName(_fromUtf8("spinBoxL10"))
        self.horizontalLayout_2.addWidget(self.spinBoxL10)
        self.spinBoxL11 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL11.setObjectName(_fromUtf8("spinBoxL11"))
        self.horizontalLayout_2.addWidget(self.spinBoxL11)
        self.spinBoxL12 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL12.setObjectName(_fromUtf8("spinBoxL12"))
        self.horizontalLayout_2.addWidget(self.spinBoxL12)
        self.spinBoxL13 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL13.setObjectName(_fromUtf8("spinBoxL13"))
        self.horizontalLayout_2.addWidget(self.spinBoxL13)
        self.spinBoxL14 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL14.setObjectName(_fromUtf8("spinBoxL14"))
        self.horizontalLayout_2.addWidget(self.spinBoxL14)
        self.spinBoxL15 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxL15.setObjectName(_fromUtf8("spinBoxL15"))
        self.horizontalLayout_2.addWidget(self.spinBoxL15)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBoxD1 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD1.setObjectName(_fromUtf8("spinBoxD1"))
        self.horizontalLayout.addWidget(self.spinBoxD1)
        self.spinBoxD2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD2.setObjectName(_fromUtf8("spinBoxD2"))
        self.horizontalLayout.addWidget(self.spinBoxD2)
        self.spinBoxD3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD3.setObjectName(_fromUtf8("spinBoxD3"))
        self.horizontalLayout.addWidget(self.spinBoxD3)
        self.spinBoxD4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD4.setObjectName(_fromUtf8("spinBoxD4"))
        self.horizontalLayout.addWidget(self.spinBoxD4)
        self.spinBoxD5 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD5.setObjectName(_fromUtf8("spinBoxD5"))
        self.horizontalLayout.addWidget(self.spinBoxD5)
        self.spinBoxD6 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD6.setObjectName(_fromUtf8("spinBoxD6"))
        self.horizontalLayout.addWidget(self.spinBoxD6)
        self.spinBoxD7 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD7.setObjectName(_fromUtf8("spinBoxD7"))
        self.horizontalLayout.addWidget(self.spinBoxD7)
        self.spinBoxD8 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD8.setObjectName(_fromUtf8("spinBoxD8"))
        self.horizontalLayout.addWidget(self.spinBoxD8)
        self.spinBoxD9 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD9.setObjectName(_fromUtf8("spinBoxD9"))
        self.horizontalLayout.addWidget(self.spinBoxD9)
        self.spinBoxD10 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD10.setObjectName(_fromUtf8("spinBoxD10"))
        self.horizontalLayout.addWidget(self.spinBoxD10)
        self.spinBoxD11 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD11.setObjectName(_fromUtf8("spinBoxD11"))
        self.horizontalLayout.addWidget(self.spinBoxD11)
        self.spinBoxD12 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD12.setObjectName(_fromUtf8("spinBoxD12"))
        self.horizontalLayout.addWidget(self.spinBoxD12)
        self.spinBoxD13 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD13.setObjectName(_fromUtf8("spinBoxD13"))
        self.horizontalLayout.addWidget(self.spinBoxD13)
        self.spinBoxD14 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD14.setObjectName(_fromUtf8("spinBoxD14"))
        self.horizontalLayout.addWidget(self.spinBoxD14)
        self.spinBoxD15 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBoxD15.setObjectName(_fromUtf8("spinBoxD15"))
        self.horizontalLayout.addWidget(self.spinBoxD15)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.scrollAreaWidgetContents)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.verticalLayout_2.addWidget(self.calendarWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.timeEdit = QtWidgets.QTimeEdit(self.scrollAreaWidgetContents)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.horizontalLayout_4.addWidget(self.timeEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.pushButtonApply = QtWidgets.QPushButton(Dialog)
        self.pushButtonApply.setObjectName(_fromUtf8("pushButtonApply"))
        self.horizontalLayout_10.addWidget(self.pushButtonApply)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_6.setText(_translate("Dialog", "Select Boxes:", None))
        self.checkBoxSelectAll.setText(_translate("Dialog", "Select All", None))
        self.label.setText(_translate("Dialog", "Select Light Cycle", None))
        self.label_4.setText(_translate("Dialog", "Cycle length:", None))
        self.label_2.setText(_translate("Dialog", "Light On Duration:", None))
        self.label_3.setText(_translate("Dialog", "Light Off Duration:", None))
        self.label_5.setText(_translate("Dialog", "Starting date:", None))
        self.pushButton.setText(_translate("Dialog", "Cancel", None))
        self.pushButtonApply.setText(_translate("Dialog", "Apply", None))

