# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wizard_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newAnalysis(object):
    def setupUi(self, newAnalysis):
        newAnalysis.setObjectName("newAnalysis")
        newAnalysis.resize(501, 392)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(newAnalysis)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(newAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.verticalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(newAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_analysis = QtWidgets.QLineEdit(newAnalysis)
        self.lineEdit_analysis.setObjectName("lineEdit_analysis")
        self.horizontalLayout_2.addWidget(self.lineEdit_analysis)
        self.pushButton_analysis = QtWidgets.QPushButton(newAnalysis)
        self.pushButton_analysis.setObjectName("pushButton_analysis")
        self.horizontalLayout_2.addWidget(self.pushButton_analysis)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(newAnalysis)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_plotting = QtWidgets.QLineEdit(newAnalysis)
        self.lineEdit_plotting.setObjectName("lineEdit_plotting")
        self.horizontalLayout_4.addWidget(self.lineEdit_plotting)
        self.pushButton_plotting = QtWidgets.QPushButton(newAnalysis)
        self.pushButton_plotting.setObjectName("pushButton_plotting")
        self.horizontalLayout_4.addWidget(self.pushButton_plotting)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(newAnalysis)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(newAnalysis)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)

        self.retranslateUi(newAnalysis)
        QtCore.QMetaObject.connectSlotsByName(newAnalysis)

    def retranslateUi(self, newAnalysis):
        _translate = QtCore.QCoreApplication.translate
        newAnalysis.setWindowTitle(_translate("newAnalysis", "New analysis wizard"))
        self.groupBox.setTitle(_translate("newAnalysis", "Analysis Type:"))
        self.radioButton.setText(_translate("newAnalysis", "Single subject"))
        self.radioButton_1.setText(_translate("newAnalysis", "Group"))
        self.radioButton_2.setText(_translate("newAnalysis", "Integrative"))
        self.label_2.setText(_translate("newAnalysis", "Path to analysis function:"))
        self.pushButton_analysis.setText(_translate("newAnalysis", "Browse..."))
        self.label.setText(_translate("newAnalysis", "Path to plotting function:"))
        self.pushButton_plotting.setText(_translate("newAnalysis", "Browse..."))
        self.pushButton_2.setText(_translate("newAnalysis", "Cancel"))
        self.pushButton.setText(_translate("newAnalysis", "Continue"))

