# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spike_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1016, 708)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.pushButton_import = QtWidgets.QPushButton(Form)
        self.pushButton_import.setObjectName("pushButton_import")
        self.verticalLayout_19.addWidget(self.pushButton_import)
        self.pushButton_load = QtWidgets.QPushButton(Form)
        self.pushButton_load.setObjectName("pushButton_load")
        self.verticalLayout_19.addWidget(self.pushButton_load)
        self.verticalLayout_21.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_31 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_18.addWidget(self.label_31)
        self.listWidget_file = QtWidgets.QListWidget(Form)
        self.listWidget_file.setMaximumSize(QtCore.QSize(16777215, 150))
        self.listWidget_file.setObjectName("listWidget_file")
        self.verticalLayout_18.addWidget(self.listWidget_file)
        self.label_20 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_18.addWidget(self.label_20)
        self.listWidget_channel = QtWidgets.QListWidget(Form)
        self.listWidget_channel.setObjectName("listWidget_channel")
        self.verticalLayout_18.addWidget(self.listWidget_channel)
        self.verticalLayout_20.addLayout(self.verticalLayout_18)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_16.addWidget(self.pushButton_save)
        self.verticalLayout_20.addLayout(self.horizontalLayout_16)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.horizontalLayout_18.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("background-color: rgb(50, 178, 38);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_30 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_38.addWidget(self.label_30)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_38.addWidget(self.comboBox_2)
        self.horizontalLayout_22.addLayout(self.verticalLayout_38)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_29 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_35.addWidget(self.label_29)
        self.comboBox_noise = QtWidgets.QComboBox(self.tab)
        self.comboBox_noise.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_noise.setObjectName("comboBox_noise")
        self.verticalLayout_35.addWidget(self.comboBox_noise)
        self.horizontalLayout_22.addLayout(self.verticalLayout_35)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_28 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_34.addWidget(self.label_28)
        self.comboBox_detection = QtWidgets.QComboBox(self.tab)
        self.comboBox_detection.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_detection.setObjectName("comboBox_detection")
        self.verticalLayout_34.addWidget(self.comboBox_detection)
        self.horizontalLayout_22.addLayout(self.verticalLayout_34)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_26 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_33.addWidget(self.label_26)
        self.comboBox_correlation = QtWidgets.QComboBox(self.tab)
        self.comboBox_correlation.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_correlation.setObjectName("comboBox_correlation")
        self.verticalLayout_33.addWidget(self.comboBox_correlation)
        self.horizontalLayout_22.addLayout(self.verticalLayout_33)
        self.verticalLayout_36.addLayout(self.horizontalLayout_22)
        spacerItem4 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_36.addItem(spacerItem4)
        self.verticalLayout_37.addLayout(self.verticalLayout_36)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_27.addWidget(self.label_21)
        self.comboBox_cluster = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_cluster.setEnabled(False)
        self.comboBox_cluster.setAutoFillBackground(False)
        self.comboBox_cluster.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_cluster.setObjectName("comboBox_cluster")
        self.verticalLayout_27.addWidget(self.comboBox_cluster)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_28)
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_15.addWidget(self.line_8)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_24.addWidget(self.label_23)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.radioButton_mean = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_mean.setObjectName("radioButton_mean")
        self.verticalLayout_23.addWidget(self.radioButton_mean)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem6)
        self.radioButton_singleWave = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_singleWave.setObjectName("radioButton_singleWave")
        self.verticalLayout_23.addWidget(self.radioButton_singleWave)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem7)
        self.radioButton_cluster = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_cluster.setObjectName("radioButton_cluster")
        self.verticalLayout_23.addWidget(self.radioButton_cluster)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem8)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.horizontalLayout_15.addLayout(self.verticalLayout_24)
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_15.addWidget(self.line_9)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_26.addWidget(self.label_24)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_26.addWidget(self.comboBox)
        self.verticalLayout_29.addLayout(self.verticalLayout_26)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem9)
        self.horizontalLayout_15.addLayout(self.verticalLayout_29)
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_15.addWidget(self.line_10)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_25.addWidget(self.label_27)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 143, 220))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.comboBox_color_1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_color_1.setEnabled(False)
        self.comboBox_color_1.setAutoFillBackground(False)
        self.comboBox_color_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_color_1.setObjectName("comboBox_color_1")
        self.horizontalLayout_19.addWidget(self.comboBox_color_1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_25.addWidget(self.scrollArea)
        self.horizontalLayout_15.addLayout(self.verticalLayout_25)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_15)
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_20.addWidget(self.line_12)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_32.addWidget(self.label_25)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 76, 237))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.checkBox_unit1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_unit1.setObjectName("checkBox_unit1")
        self.horizontalLayout_21.addWidget(self.checkBox_unit1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_32.addWidget(self.scrollArea_2)
        self.horizontalLayout_20.addLayout(self.verticalLayout_32)
        self.pushButton_accept = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_accept.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout_20.addWidget(self.pushButton_accept)
        self.verticalLayout_31.addLayout(self.horizontalLayout_20)
        self.line_11 = QtWidgets.QFrame(self.tab_2)
        self.line_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_31.addWidget(self.line_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_none = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_none.setObjectName("radioButton_none")
        self.verticalLayout.addWidget(self.radioButton_none)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.radioButton_sleep = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_sleep.setObjectName("radioButton_sleep")
        self.verticalLayout.addWidget(self.radioButton_sleep)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.radioButton_behavior = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_behavior.setObjectName("radioButton_behavior")
        self.verticalLayout.addWidget(self.radioButton_behavior)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.radioButton_externaltrigger = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_externaltrigger.setObjectName("radioButton_externaltrigger")
        self.verticalLayout.addWidget(self.radioButton_externaltrigger)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem15)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_psth = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_psth.setObjectName("radioButton_psth")
        self.verticalLayout_3.addWidget(self.radioButton_psth)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem16)
        self.radioButton_raster = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_raster.setObjectName("radioButton_raster")
        self.verticalLayout_3.addWidget(self.radioButton_raster)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.radioButton_raw = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_raw.setObjectName("radioButton_raw")
        self.verticalLayout_3.addWidget(self.radioButton_raw)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.radioButton_waveforms = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_waveforms.setObjectName("radioButton_waveforms")
        self.verticalLayout_3.addWidget(self.radioButton_waveforms)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.radioButton_events = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_events.setObjectName("radioButton_events")
        self.verticalLayout_3.addWidget(self.radioButton_events)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_14.addWidget(self.line_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.doubleSpinBox_binning = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_binning.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_binning.setObjectName("doubleSpinBox_binning")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_binning)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_14.addWidget(self.line_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem24)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.doubleSpinBox_min = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_min.setObjectName("doubleSpinBox_min")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_min)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.doubleSpinBox_max = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_max.setObjectName("doubleSpinBox_max")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_max)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem25)
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_14.addWidget(self.line_4)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem26)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem27)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem28)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.doubleSpinBox_startSpk = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startSpk.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_startSpk.setObjectName("doubleSpinBox_startSpk")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_startSpk)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.doubleSpinBox_stopSpk = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopSpk.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_stopSpk.setObjectName("doubleSpinBox_stopSpk")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_stopSpk)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_17.addLayout(self.verticalLayout_12)
        self.line_6 = QtWidgets.QFrame(self.tab_3)
        self.line_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_17.addWidget(self.line_6)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.verticalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem31)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.doubleSpinBox_startSleep = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startSleep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_startSleep.setObjectName("doubleSpinBox_startSleep")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_startSleep)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.doubleSpinBox_stopSleep = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopSleep.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_stopSleep.setObjectName("doubleSpinBox_stopSleep")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_stopSleep)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout_17.addLayout(self.verticalLayout_13)
        self.line_7 = QtWidgets.QFrame(self.tab_3)
        self.line_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_17.addWidget(self.line_7)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_11.addWidget(self.label_16)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem33)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_12)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.doubleSpinBox_startBehav = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_startBehav.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_startBehav.setObjectName("doubleSpinBox_startBehav")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_startBehav)
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.doubleSpinBox_stopBehav = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_stopBehav.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_stopBehav.setObjectName("doubleSpinBox_stopBehav")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_stopBehav)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem35)
        self.horizontalLayout_14.addLayout(self.verticalLayout_17)
        self.verticalLayout_30.addLayout(self.horizontalLayout_14)
        self.line_5 = QtWidgets.QFrame(self.tab_3)
        self.line_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_30.addWidget(self.line_5)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem36)
        self.line_5.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_22.addWidget(self.tabWidget)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem37 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem37)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_17.addWidget(self.pushButton_cancel)
        self.pushButton_done = QtWidgets.QPushButton(Form)
        self.pushButton_done.setObjectName("pushButton_done")
        self.horizontalLayout_17.addWidget(self.pushButton_done)
        self.verticalLayout_22.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_22)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_18)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_import.setText(_translate("Form", "Import data"))
        self.pushButton_load.setText(_translate("Form", "Load data"))
        self.label_31.setText(_translate("Form", "Select dataset:"))
        self.label_20.setText(_translate("Form", "Select channel:"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.label_30.setText(_translate("Form", "Reference"))
        self.label_29.setText(_translate("Form", "Non linear energy operator"))
        self.label_28.setText(_translate("Form", "Detection criteria"))
        self.label_26.setText(_translate("Form", "Correlation criteria"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Detection"))
        self.label_21.setText(_translate("Form", "Cluster"))
        self.label_23.setText(_translate("Form", "Waveforms"))
        self.radioButton_mean.setText(_translate("Form", "Mean"))
        self.radioButton_singleWave.setText(_translate("Form", "Single waveforms"))
        self.radioButton_cluster.setText(_translate("Form", "Cluster"))
        self.label_24.setText(_translate("Form", "Session"))
        self.label_27.setText(_translate("Form", "Color"))
        self.label_22.setText(_translate("Form", "Unit1"))
        self.label_25.setText(_translate("Form", "Change unit"))
        self.checkBox_unit1.setText(_translate("Form", "unit 1"))
        self.pushButton_accept.setText(_translate("Form", "Accept"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Sorting"))
        self.label.setText(_translate("Form", "Events"))
        self.radioButton_none.setText(_translate("Form", "None"))
        self.radioButton_sleep.setText(_translate("Form", "Sleep"))
        self.radioButton_behavior.setText(_translate("Form", "Behavior"))
        self.radioButton_externaltrigger.setText(_translate("Form", "External trigger"))
        self.label_2.setText(_translate("Form", "Plot"))
        self.radioButton_psth.setText(_translate("Form", "PSTH"))
        self.radioButton_raster.setText(_translate("Form", "Raster"))
        self.radioButton_raw.setText(_translate("Form", "Raw"))
        self.radioButton_waveforms.setText(_translate("Form", "Waveform"))
        self.radioButton_events.setText(_translate("Form", "Events"))
        self.label_3.setText(_translate("Form", "Binning"))
        self.label_4.setText(_translate("Form", "Range"))
        self.label_5.setText(_translate("Form", "Min"))
        self.label_6.setText(_translate("Form", "Max"))
        self.label_7.setText(_translate("Form", "-"))
        self.label_8.setText(_translate("Form", "Neuronal activity"))
        self.label_9.setText(_translate("Form", "Start"))
        self.label_10.setText(_translate("Form", "Stop"))
        self.label_11.setText(_translate("Form", "-"))
        self.label_12.setText(_translate("Form", "Sleep"))
        self.label_13.setText(_translate("Form", "Start"))
        self.label_14.setText(_translate("Form", "Stop"))
        self.label_15.setText(_translate("Form", "-"))
        self.label_16.setText(_translate("Form", "Behavior"))
        self.label_17.setText(_translate("Form", "Start"))
        self.label_18.setText(_translate("Form", "Stop"))
        self.label_19.setText(_translate("Form", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Analysis"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_done.setText(_translate("Form", "Done"))

